name: Build

on:
  push:
  pull_request:

jobs:
  build-all:
    name: CMake - ${{ matrix.platform[0] }} - ${{ matrix.platform[2] }}
    runs-on: ${{ matrix.platform[1] }}
    strategy:
      matrix:
        platform:
          - [Windows, windows-latest, msvc, debug]
          - [Windows, windows-latest, msvc, release]
          - [Windows, windows-latest, gcc, debug]
          - [Windows, windows-latest, gcc, release]
          - [Windows, windows-latest, clang, debug]
          - [Windows, windows-latest, clang, release]
          - [Linux, ubuntu-latest, gcc, debug]
          - [Linux, ubuntu-latest, gcc, release]
          - [Linux, ubuntu-latest, clang, debug]
          - [Linux, ubuntu-latest, clang, release]
    steps:
      - uses: actions/checkout@v3
  
      - name: Install MinGW-w64
        if: matrix.platform[2] == 'gcc'
        uses: mattn/mingw-action@v2
      
      - name: Set env vars for GCC
        if: matrix.platform[2] == 'gcc'
        run: echo "CC=gcc" >> $GITHUB_ENV && echo "CXX=g++" >> $GITHUB_ENV
      
      - name: Install Clang
        if: matrix.platform[2] == 'clang'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"
      
      - name: Set env vars for Clang
        if: matrix.platform[2] == 'clang'
        run: echo "CC=clang" >> $GITHUB_ENV && echo "CXX=clang++" >> $GITHUB_ENV

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.platform[3] }}

      - name: Build
        run: cmake --build build --parallel --config ${{ matrix.platform[3] }}

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: |
            build/**/**/**/test/${{ matrix.platform[3] }}/*.exe
            build/lib/**/*.so*
            bin/
            src/version*.*
